Create templating of website
MytiX/SnowTricks pull request #12
Opened 2022-03-16 08:02 UTC by MytiX

2022-03-18 17:03 UTC, maitre-hibou requested changes
Je te laisse faire les correctifs avec un en plus ; plutôt que d'inclure les fichiers de Bootstrap, enlèves-les de ton dépôt et utilise le CDN. Ca raccourcira ton code.

2022-03-18 17:03 UTC, maitre-hibou commented on src/Tricks/Controller/EditTricksController.php
> +    public function index(?int $id = null): Response
Encore pareil qu'au dessus :)

2022-03-25 08:29 UTC, MytiX commented on config/routes/annotations.yaml
> +security-controllers:
Mise à jour : passer en camelCase

2022-03-25 08:29 UTC, MytiX commented on config/routes/annotations.yaml
> +tricks-controllers:
Mise à jour : passer en camelCase

2022-03-25 08:31 UTC, MytiX commented on src/Controller/HomeController.php
> +    public function index(): Response
Changed

2022-03-25 08:31 UTC, MytiX commented on src/Security/Controller/ForgotPasswordController.php
> +    public function index(): Response
Changed

2022-03-25 08:31 UTC, MytiX commented on src/Security/Controller/ResetPasswordController.php
> +    public function index(): Response
Changed

2022-03-25 08:31 UTC, MytiX commented on src/Security/Controller/SignInController.php
> +    public function index(): Response
Changed

2022-03-25 08:31 UTC, MytiX commented on src/Security/Controller/SignUpController.php
> +    public function index(): Response
Changed

2022-03-25 08:32 UTC, MytiX commented on src/Tricks/Controller/EditTricksController.php
> +    public function index(?int $id = null): Response
Changed

2022-03-25 08:32 UTC, MytiX commented on src/Tricks/Controller/TricksDetailController.php
> +    public function index(string $slug): Response
Changed

2022-03-25 08:33 UTC, merged