Tricks
MytiX/SnowTricks pull request #14
Opened 2022-03-25 08:41 UTC by MytiX

2022-05-06 20:47 UTC, maitre-hibou requested changes
Quelques petits trucs a modifier, et on reparlera de certains points a la prochaine session !

2022-05-06 20:47 UTC, maitre-hibou commented on public/assets/js/media.js
> +            console.log(link_delete)
Attention a bien supprimer les console.log de ton code

2022-05-06 20:47 UTC, maitre-hibou commented on src/Media/Controller/MediaController.php
> +    #[Route('/media/delete/{id}', name: 'app_delete_media', methods: 'DELETE')]
Pour les url de tes routes de type API, tu peux utiliser la nomenclature REST. Par exemple, ici, tu appelle cette route avec la methode DELETE, il est donc possible de simplifier l'url comme ca : `/media/{id}`

2022-05-06 20:47 UTC, maitre-hibou commented on src/Media/Controller/MediaController.php
> +    #[Route('/media/header/{tricks_id}/{media_id}', name: 'app_header_media', methods: 'PUT')]
La prochaine fois, on reparlera du nommage des routes :)

2022-05-06 20:47 UTC, maitre-hibou commented on src/Media/Controller/MediaController.php
> +    public function header(int $tricks_id, int $media_id, Request $request, TricksRepository $tricksRepository, EntityManagerInterface $em)
Pour le nommage des variable, il serait mieux d'utiliser des noms qui sont bien compréhensibles. Par exemple, pour `$em` qui représente l'entity manager, il vaudrait mieux un `$entityManager`

2022-05-06 20:47 UTC, maitre-hibou commented on src/Media/Repository/MediaRepository.php
> +    // /**
Si ce code n'est pas utilisé, supprime le plutot que de le laisser en commentaire

2022-06-18 15:50 UTC, MytiX commented on public/assets/js/media.js
> +            console.log(link_delete)
Patch

2022-06-18 15:50 UTC, MytiX commented on src/Media/Controller/MediaController.php
> +    #[Route('/media/delete/{id}', name: 'app_delete_media', methods: 'DELETE')]
Patch

2022-06-18 15:50 UTC, MytiX commented on src/Media/Controller/MediaController.php
> +    #[Route('/media/header/{tricks_id}/{media_id}', name: 'app_header_media', methods: 'PUT')]
Patch

2022-06-18 15:51 UTC, MytiX commented on src/Media/Controller/MediaController.php
> +    public function header(int $tricks_id, int $media_id, Request $request, TricksRepository $tricksRepository, EntityManagerInterface $em)
Patch

2022-06-18 15:51 UTC, MytiX commented on src/Media/Repository/MediaRepository.php
> +    // /**
Patch

2022-06-18 16:07 UTC, merged